LibrApp2/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibrApp2.Models;
using LibrApp2.ViewModels;
using Microsoft.AspNet.Identity;

namespace LibrApp2.Controllers
{
    public class ReviewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public void CalculateAverageRating(int bookId, byte rate)
        {
            Book book = db.Books.Include(b => b.Reviews).SingleOrDefault(b => b.Id == bookId);

            if (book == null)
                throw new HttpException(404, "404 Not Found");

            float maxRating = 0;
            foreach (Review review in book.Reviews)
            {
                maxRating += review.Rate;
            }
            book.AverageRating = maxRating / book.Reviews.Count;
            book.AverageRating = (float)Math.Round(book.AverageRating, 2);
        }

        public ActionResult ShowReviews(int id)
        {
            var currentBook = db.Books.Include(b => b.Reviews).SingleOrDefault(b => b.Id == id);
            var reviews = currentBook.Reviews.ToList();

            if (currentBook == null || reviews == null)
                return HttpNotFound();

            return View(reviews);
        }

        public ActionResult AdminShowSingleReview(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

           
            var review = db.Reviews.SingleOrDefault(r => r.Id == id);

            if (review == null)
                return HttpNotFound();

            return View("ShowSingleReview", review);
        }

        public ActionResult ShowSingleReview(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userId = User.Identity.GetUserId();
            var review = db.Reviews.SingleOrDefault(r => r.BookId == id && r.UserProfile.AspNetUserId == userId);

            if (review == null)
                return HttpNotFound();

            return View(review);
        }

        [Authorize]
        public ActionResult AddReview(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult AddReview([Bind(Include = "Id, Content, Rate")] Review review, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                review.BookId = (int)id;
                string userId = User.Identity.GetUserId();
                UserProfile userProfile = db.UserProfiles.SingleOrDefault(u => u.AspNetUserId == userId);
                review.UserProfile = userProfile;
                if (!db.Reviews.Where(
                    r => r.UserProfile.AspNetUserId == review.UserProfile.AspNetUserId && r.BookId == review.BookId).Any())
                {

                    db.Reviews.Add(review);
                    CalculateAverageRating(review.BookId, review.Rate);
                    db.SaveChanges();
                    return RedirectToAction("MyBookshelf", "Books");
                }
            }
            return View(review);
        }

        // GET: Reviews
        [Authorize(Roles = RoleName.Admin)]
        public ActionResult Index()
        {
            var reviews = db.Reviews.Include(r => r.Book).Include(r => r.UserProfile).ToList();
            return View(reviews);
        }

        // GET: Reviews/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.SingleOrDefault(r => r.Id == id);
            

            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Content,Rate,BookId,UserProfileId")] Review review)
        {
            if (ModelState.IsValid)
            {
                if (User.IsInRole(RoleName.Admin))
                {
                    var userId = this.User.Identity.GetUserId();
                    String adminProfileUsername = db.UserProfiles.SingleOrDefault(u => u.AspNetUserId == userId).Username;
                    review.Content = review.Content.Insert(review.Content.Length, "\n[This review was edited by one of administrators (" + adminProfileUsername + ")]");
                }
                db.Entry(review).State = EntityState.Modified;
                CalculateAverageRating(review.BookId, review.Rate);
                db.SaveChanges();


                return RedirectToAction("MyBookshelf", "Books", new { id = review.UserProfileId });
            }
            return View(review);
        }

        // GET: Books/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Books/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Review review = db.Reviews.Find(id);
            db.Reviews.Remove(review);
            CalculateAverageRating(review.BookId, review.Rate);
            db.SaveChanges();
            return RedirectToAction("MyBookshelf", "Books", new { id = review.UserProfileId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LibrApp2/Controllers/UserProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibrApp2.Models;
using Microsoft.AspNet.Identity;

namespace LibrApp2.Controllers
{
    public class UserProfilesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: UserProfiles
        [Authorize(Roles = RoleName.Admin)]
        public ActionResult Index()
        {
            return View(db.UserProfiles.ToList());
        }

        // GET: UserProfiles/Details/5
        public ActionResult OwnProfileDetails()
        {
            String userId = User.Identity.GetUserId();
            UserProfile userProfile = db.UserProfiles.SingleOrDefault(u => u.AspNetUserId == userId);
            if (userProfile == null)
            {
                return HttpNotFound();
            }

            return View(userProfile);
        }

        // GET: UserProfiles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // GET: UserProfiles/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: UserProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,AspNetUserId,Username")] UserProfile userProfile)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.UserProfiles.Add(userProfile);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(userProfile);
        //}

        // GET: UserProfiles/Edit/5
        [Authorize(Roles = RoleName.Admin)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // POST: UserProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = RoleName.Admin)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AspNetUserId,Username")] UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userProfile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userProfile);
        }

        // GET: UserProfiles/Delete/5
        [Authorize(Roles = RoleName.Admin)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // POST: UserProfiles/Delete/5
        [Authorize(Roles = RoleName.Admin)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userProfile = db.UserProfiles.Find(id);
            var aspNetUser = db.Users.SingleOrDefault(u => u.Id == userProfile.AspNetUserId);
            db.UserProfiles.Remove(userProfile);
            db.Users.Remove(aspNetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

LibrApp2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - LibrApp2</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LibrApp2/Views/Shared/_NavBar.cshtml
@using LibrApp2.Models
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("LibrApp2", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Books", "IndexAPI", "Books")</li>
                <li>@Html.ActionLink("My Bookshelf", "MyBookshelf", "Books")</li>
                <li>@Html.ActionLink("Authors", "Index", "Authors")</li>
                @if (User.IsInRole("Admin"))
                {
                    <li>@Html.ActionLink("All users", "Index", "UserProfiles")</li>
                    <li>@Html.ActionLink("All reviews", "Index", "Reviews")</li>
                }
                <li>@Html.ActionLink("About", "About", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

LibrApp2/Views/Shared/_deleteModalPopUp.cshtml
<div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to permanently delete this record from the database? <br />(Warning: This action cannot be undone)
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary js-close btn-sm" id="reset" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-default js-ok btn-sm">Save changes</button>
            </div>
        </div>
    </div>
</div>